### ISSUE TITLE
Bindings for StateFlow

### ISSUE THREAD

**Issue by lukasz-kalnik-gcx** [icerockdev/moko-mvvm#165]
Is adding support for StateFlow considered?
Is this library under active development (i.e. do you plan support for Jetpack Compose and Kotlin StateFlow)?

**Comment by Alex009** [comment]
yes, StateFlow will be supported later, after implementation of https://github.com/icerockdev/moko-kswift/issues/27

also you can use StateFlow and now, but it will require manual additions of binding functions.

jetpack compose supported also out of box just because compose support LiveData to State conversion

**Comment by Alex009** [comment]
will be available in 0.13.0 in `mvvm-flow` module
