### ISSUE TITLE
Append iOS-specific ability for memory collecting

### ISSUE THREAD

**Issue by DevTchernov** [icerockdev/moko-mvvm#23]
Same as follow:
```
actual open class ViewModel actual constructor() {
    ...
    fun collectMemory() {
    	kotlin.native.internal.GC.collect()
    }
}
```

**Comment by Alex009** [comment]
why you think that it should be in `ViewModel`? maybe just global fun in ios-specific part?

**Comment by Alex009** [comment]
so i add `GC.collect` to `onCleared` of `ViewModel` in ios...it will be automatically

**Comment by Alex009** [comment]
merged

**Comment by schrulnz** [comment]
I have a question about this: Why do you think `GC.collect()` is needed here? Isn't the garbage collection called automatically by Kotlin anyways?

**Comment by Alex009** [comment]
hi.
we found that GC of Kotlin/Native not syncronized with swift part memory management. it's bring us to high memory usage, when swift part have many object and K/N not call GC yet, because think that it can wait. 

another reason is that in swift part ios developers sometimes use `deinit` function with some logic and expect that this logic will be called immediately but if object was catched by Kotlin/Native this call will be delayed, wait for GC. 

with automatically call GC.collect we solve for us both problems
