### ISSUE TITLE
Separate library to multiple artifacts

### ISSUE THREAD

**Issue by ausichenko** [icerockdev/moko-mvvm#65]
It would be nice to see the new **moko-viewmodel** or **moko-mvvm-viewmodel** library. Without **databinding** support for declarative UI - _**Jetpack Compose**_.

And the **moko-mvvm** library can be updated by composing from **moko-viewmodel**, **moko-livedata** (for the future, as an example)

**Comment by ln-12** [comment]
I would also like to see the equivalent for https://developer.android.com/jetpack/compose/state#viewmodel-and-jetpack-compose

**Comment by Alex009** [comment]
@ln-12 what exactly you like to see? moko-mvvm provide original jetpack's viewmodels, so all integration with compose is already available

**Comment by Alex009** [comment]
Suggested modules:
- mvvm-viewmodel (viewmodel, eventdispatcher)
- mvvm-livedata (livedata, transform, state)
- mvvm-databinding (all databinding, depends on viewmodel, livedata)
- mvvm (depends on all modules)

**Comment by ln-12** [comment]
@Alex009 For example the `ViewModel for login feature` section in the readme only deals with data bindings. It would be nice to see it with compose :)

**Comment by Link184** [comment]
> Suggested modules:
> 
> * mvvm-viewmodel (viewmodel, eventdispatcher)
> * mvvm-livedata (livedata, transform, state)
> * mvvm-databinding (all databinding, depends on viewmodel, livedata)
> * mvvm (depends on all modules)

for `mvvm-viewmodel` I think `viewmodel` should be a mandatory part of `mvvm` architecture at leas because the last 2 letters from `mvvm` means `viewmodel`. Also I think another dependencies(like databinding or uicompose) should be delivered separately because they have nothing in common with `mvvm` principles, they should act more like additional helper tools, maybe connected like plugins(like gson-converter for retrofit). That means less dependencies and less potential dependencies conflicts and frustrations on consumer projects.

**Comment by Alex009** [comment]
will be released in 0.9.0
